### ISSUE TITLE
进行并行测试过程中，出现俩路并行的返回参数会相互串到一起

### ISSUE THREAD

**Issue by liaohuan2613** [attemper/attemper#2]
问题出现在1.0.1分支
![image](https://user-images.githubusercontent.com/26337403/77614694-8660e380-6f68-11ea-8024-197658709d27.png)
4号和7号会拿到前面所有节点向后传输的数据

**Comment by ldang264** [comment]
是这样的，返回参数是属于全局的，产生后即会绑定给整个任务流
